# Generated by Django 4.2.8 on 2023-12-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='image_api.gallery'),
        ),
    ]
