# Generated by Django 4.2.8 on 2023-12-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_api', '0004_alter_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.URLField(default=''),
        ),
    ]
